personalWeb/urls.py
from django.contrib import admin
from django.views.static import serve
from django.urls import path, include, re_path
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photoWeb.urls', namespace='photoWeb')),
    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
]

photoWeb/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'photoWeb'


urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('grid', views.grid, name='grid'),
    path('masonry', views.masonry, name='masonry'),
    path('blog', views.blog, name='blog'),
    path('single_post', views.single_post, name='single_post'),
    path('about', views.about, name='about'),

    path('get_message_from_user', views.get_message_from_user, name='get_message_from_user'),
    path('get_photo_page', views.get_photo_page, name='get_photo_page'),
    path('get_blog_page', views.get_blog_page, name='get_blog_page'),

    path('post_photo_blog_from_user', views.post_photo_blog_from_user, name='post_photo_blog_from_user'),
    path('get_all_categories', views.get_all_categories, name='get_all_categories'),
    path('get_all_cameras', views.get_all_cameras, name='get_all_cameras'),
]

photoWeb/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Cameraman(models.Model):
    id = models.AutoField("摄影师ID", primary_key=True)
    name = models.CharField("名字", max_length=40, default="Null")
    description = models.TextField("介绍", max_length=400, default="无")
    mark = models.TextField("标注", max_length=400, default="默认标注")
    created_at = models.DateTimeField("添加日期", auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_at']
        verbose_name = '摄影师信息表'
        verbose_name_plural = '摄影师信息表'


class Category(models.Model):
    id = models.AutoField("风格ID", primary_key=True)
    name = models.CharField("风格", max_length=40, default="默认风格")
    mark = models.TextField("标注", max_length=400, default="默认标注")
    created_at = models.DateTimeField("添加日期", auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_at']
        verbose_name = '风格信息表'
        verbose_name_plural = '风格信息表'


class Blog(models.Model):
    id = models.AutoField("日志id", primary_key=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="风格")
    cameraman = models.ForeignKey(Cameraman, on_delete=models.CASCADE, verbose_name="摄影师")
    title = models.CharField("标题", max_length=100, default="默认标题")
    imgLevel1 = models.ImageField("图片1", upload_to="photo_web_img", help_text="最大尺寸")
    imgLevel2 = models.ImageField("图片2", upload_to="photo_web_img", help_text="第二大尺寸")
    imgLevel3 = models.ImageField("图片3", upload_to="photo_web_img", help_text="第三大尺寸")
    description = models.TextField("简介", max_length=400, default="无")
    content = models.TextField("日志内容", max_length=1000, default="默认日志内容")
    created_at = models.DateTimeField("添加日期", auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']
        verbose_name = '日志信息表'
        verbose_name_plural = '日志信息表'


class FeedBack(models.Model):
    id = models.AutoField("反馈id", primary_key=True)
    name = models.TextField('名字', max_length=100, default='None', help_text='用户填的名字')
    email = models.EmailField('邮箱地址', max_length=254, help_text='O.O')
    message = models.TextField('反馈内容', max_length=2000, help_text='长度不确定，暂时设为最长2000')
    created_at = models.DateTimeField("添加日期", auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_at']
        verbose_name = '反馈信息表'
        verbose_name_plural = '反馈信息表'

photoWeb/views.py
import json

from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from django.forms.models import model_to_dict
from django.views.static import serve

from local_struct import CJSONEncoder
from local_struct.page_data import PageData
from local_struct.result_client import ResultClient
from personalWeb.settings import MEDIA_ROOT, MEDIA_DIR, MEDIA_URL
from .models import *
import math

# Create your views here.
'''
页面使用的接口
'''


def index(request):
    photos = get_photo_by_page()
    return render(request, 'photoWeb/index.html', {'photos': photos})


def grid(request):
    photos = get_photo_by_page()
    return render(request, 'photoWeb/grid.html', {'photos': photos})


def masonry(request):
    photos = get_photo_by_page()
    return render(request, 'photoWeb/masonry.html', {'photos': photos})


def get_photo_page(request):
    if request.method == "GET":
        pageNumber = int(request.GET.get('pageNumber', 1))
        pageSize = int(request.GET.get('pageSize', 9))
        res = get_photo_by_page(pageNumber, pageSize)
        total_page = math.ceil(len(Blog.objects.all()) / pageSize)
        data = PageData(pageNumber, pageSize, total_page, res)
        data = json.dumps(data, default=lambda obj:obj.__dict__, sort_keys=True, indent=4, ensure_ascii=False)
        print(pageNumber)
        return HttpResponse(data)
    else:
        return HttpResponse(None)


def blog(request):
    data = {}
    blog_data = get_blog_by_page()
    data["blogs"] = blog_data
    data["categories"] = get_blog_to_num_by_categories()
    data["recent_imgs"] = get_recent_8_img()
    data["recent_cameraman"] = get_blog_by_page()

    return render(request, 'photoWeb/blog.html', {'data': data})


def get_blog_page(request):
    if request.method == "GET":
        pageNumber = int(request.GET.get('pageNumber', 1))
        pageSize = int(request.GET.get('pageSize', 3))
        res = get_blog_by_page(pageNumber, pageSize)
        total_page = math.ceil(len(Blog.objects.all()) / pageSize)
        data = PageData(pageNumber, pageSize, total_page, res)
        data = json.dumps(data, default=lambda obj: obj.__dict__, sort_keys=True, indent=4, ensure_ascii=False)
        return HttpResponse(data)
    return None


def single_post(request):
    get_recent_7_month_blog()
    if not request.GET.get('id'):
        if len(Blog.objects.all()) > 0:
            blog = Blog.objects.first()
            blog_dic = model_to_dict(blog)
            blog_dic['created_at'] = blog.created_at.strftime('%Y-%m-%d')
            blog_dic['cameraman'] = Cameraman.objects.get(id=blog_dic['cameraman']).name
            blog_dic['category'] = Category.objects.get(id=blog_dic['category']).name
            data = {}
            data['blog'] = blog_dic
            data["categories"] = get_blog_to_num_by_categories()
            data["recent_imgs"] = get_recent_8_img()
            data["recent_cameraman"] = get_blog_by_page()
            return render(request, 'photoWeb/single-post.html', {'data': data})
        else:
            return HttpResponse(None)
    else:
        blog_id = int(request.GET['id'])
        blog = Blog.objects.get(id=blog_id)
        blog_dic = model_to_dict(blog)
        blog_dic['created_at'] = blog.created_at.strftime('%Y-%m-%d')
        blog_dic['cameraman'] = Cameraman.objects.get(id=blog_dic['cameraman']).name
        blog_dic['category'] = Category.objects.get(id=blog_dic['category']).name
        data = {}
        data['blog'] = blog_dic
        data["categories"] = get_blog_to_num_by_categories()
        data["recent_imgs"] = get_recent_8_img()
        data["recent_cameraman"] = get_blog_by_page()
        return render(request, 'photoWeb/single-post.html', {'data': data})


def about(request):
    return render(request, 'photoWeb/about.html')


def get_message_from_user(request):
    """
    POST方式获取用户上传的消息
    :param request:
    name, email, message
    :return:
    true: 上传成功， false: 上传失败
    """
    res = False
    print('message')
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        if name and email and message:
            res = True
            fd = FeedBack(name = name, email = email, message = message)
            fd.save()
            print(fd)
    return HttpResponse(json.dumps({'result': res}))


@csrf_exempt
def post_photo_blog_from_user(request):
    """
    上传blog日志
    :param request:
    :return:
    """
    res = 'Fail'
    if request.method == 'POST':
        category = Category.objects.get(id = int(request.POST.get('category')))
        cameraman = Cameraman.objects.get(id = int(request.POST.get('cameraman')))
        title = request.POST.get('title')
        description = request.POST.get('description')
        content = request.POST.get('content')
        imgLevel1 = request.FILES.get('imgLevel1')
        imgLevel2 = request.FILES.get('imgLevel2')
        imgLevel3 = request.FILES.get('imgLevel3')
        b = Blog()
        b.category = category
        b.cameraman = cameraman
        b.title = title
        b.description = description
        b.content = content
        b.imgLevel1 = imgLevel1
        b.imgLevel2 = imgLevel2
        b.imgLevel3 = imgLevel3
        b.save()
        res = 'Succ'
    return HttpResponse(res)


def get_all_categories(request):
    """
    获取所有的风格信息
    :param request:
    :return:
    """
    rc = ResultClient()
    if request.method == 'GET':
        categories = Category.objects.values()
        rc.result = list(categories)
    else:
        rc.code = 50
        rc.msg = '请求方式错误'
    return HttpResponse(json.dumps(rc.__dict__, ensure_ascii=False, cls=CJSONEncoder.CJSONEncoder),
                        content_type="application/json")


def get_all_cameras(request):
    """
    获取所有的摄影师信息
    :param request:
    :return:
    """
    rc = ResultClient()
    if request.method == 'GET':
        cameras = Cameraman.objects.values()
        rc.result = list(cameras)
    else:
        rc.code = 50
        rc.msg = '请求方式错误'
    return HttpResponse(json.dumps(rc.__dict__, ensure_ascii=False, cls=CJSONEncoder.CJSONEncoder),
                        content_type="application/json")


'''
逻辑操作
'''


def get_photo_by_page(page_num=1, page_size=9):
    photos = Blog.objects.values_list('id', 'imgLevel1', 'title', 'category', 'description')
    p = list(photos)
    if photos:
        start_num = (page_num - 1) * page_size
        end_num = page_num * page_size
        if len(p) >= start_num:
            if len(p) >= end_num:
                pass
            else:
                end_num = len(p)
        else:
            return None
        p = p[start_num:end_num]
        keys = ['id', 'imgLevel1', 'title', 'category', 'description']
        dic = [dict(zip(keys, item)) for item in p]
        for item in dic:
            item['category'] = Category.objects.get(id=item['category']).name
        return dic
    return None


def get_blog_by_page(page_num=1, page_size=3):
    photos = Blog.objects.values_list('id', 'imgLevel1', 'imgLevel2','imgLevel3', 'cameraman', 'category', 'title', 'content', 'created_at')
    p = list(photos)
    if photos:
        start_num = (page_num - 1) * page_size
        end_num = page_num * page_size
        if len(p) >= start_num:
            if len(p) >= end_num:
                pass
            else:
                end_num = len(p)
        else:
            return None
        p = p[start_num:end_num]
        keys = ['id', 'imgLevel1', 'imgLevel2','imgLevel3', 'cameraman', 'category', 'title', 'content', 'created_at']
        dic = [dict(zip(keys, item)) for item in p]
        for item in dic:
            item['category'] = Category.objects.get(id=item['category']).name
            item['cameraman'] = Cameraman.objects.get(id=item['cameraman']).name
            item['created_at'] = item['created_at'].strftime('%Y-%m-%d')
        return dic
    return None


def get_blog_to_num_by_categories():
    """
    获取每个风格的名字以及对应的数量
    [{"id":id, "category":category,"num":num}, ...]
    """
    categories = Category.objects.all()
    categories_list = []
    for item in categories:
        num = Blog.objects.filter(category__id=item.id).count()
        dic = {}
        dic['id'] = item.id
        dic["category"] = item.name
        dic["num"] = num
        categories_list.append(dic)
    return categories_list


def get_recent_8_img():
    """
    获取最近的8张图
    :return:
    imgLevel3
    """
    imgs = Blog.objects.values('id', 'imgLevel3')
    tar_imgs = []
    if imgs:
        if len(imgs) >= 8:
            tar_imgs = list(imgs[:8])
        else:
            tar_imgs = list(imgs[:len(imgs)])
    return tar_imgs


def get_recent_7_month_blog():
    """
    获取前七个月的日志数量
    :return:
    [{}, ...]
    """
    date_arr = Blog.objects.values_list('created_at')
    date_dic = {}
    # for date_m_d in date_arr:
    #     key = date_m_d.strftime('%Y-%m-%d')
    #     if key not in date_dic.keys():
    #         date_dic[key]=key

    print(date_dic)
    return None

templates/photoWeb/base.html
<html lang="">
    <head>
        {% load static %}

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  		<title>ZooTankB</title>

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="{% static 'photoWeb/favicon.ico' %}">

        <link rel="stylesheet" href="{% static 'photoWeb/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'photoWeb/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'photoWeb/css/fontAwesome.css' %}">
        <link rel="stylesheet" href="{% static 'photoWeb/css/light-box.css' %}">
        <link rel="stylesheet" href="{% static 'photoWeb/css/templatemo-style.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Kanit:100,200,300,400,500,600,700,800,900" rel="stylesheet">

        <script src="{% static 'photoWeb/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>

<body>

    <nav>
        <div class="logo">
            <a href="{% url 'photoWeb:index' %}">Yang<em>Rong</em></a>
        </div>
        <div class="menu-icon">
        <span></span>
      </div>
    </nav>

    {% block main_data %}
        <h1>This is the base.html</h1>
    {% endblock %}

    <footer>
        <div class="container-fluid">
            <div class="col-md-12">
                <p>Copyright &copy; Template mo 2018 YangRong
    | More Info <a href="#" target="_blank" title="荣荣和小橙子">YangRong</a> - Collect from <a href="#" title="荣荣和小橙子" target="_blank">YangRong</a></p>
            </div>
        </div>
    </footer>


      <!-- Modal button -->
    <div class="popup-icon">
      <button id="modBtn" class="modal-btn"><img src="{% static 'photoWeb/img/contact-icon.png' %}" alt=""></button>
    </div>

    <!-- Modal -->
    <div id="modal" class="modal">
      <!-- Modal Content -->
      <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
          <h3 class="header-title">Say hello to <em>Highway</em></h3>
          <div class="close-btn"><img src="{% static 'photoWeb/img/close_contact.png' %}" alt=""></div>
        </div>
        <!-- Modal Body -->
        <div class="modal-body">
          <div class="col-md-6 col-md-offset-3">
            <form id="contact" action="" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-12">
                      <fieldset>
                          <label for="name"></label><input name="name" type="text" class="form-control" id="name" placeholder="Your name..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                          <label for="email"></label><input name="email" type="email" class="form-control" id="email" placeholder="Your email..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                          <label for="message"></label><textarea name="message" rows="6" class="form-control" id="message" placeholder="Your message..." required></textarea>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <button type="submit" id="form-submit" class="btn" onclick="postMessage()">Send Message Now</button>
                      </fieldset>
                    </div>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>



    <section class="overlay-menu">
      <div class="container">
        <div class="row">
          <div class="main-menu">
              <ul>
                  <li>
                      <a href="{% url 'photoWeb:index' %}">Home - Full-width</a>
                  </li>
                  <li>
                      <a href="{% url 'photoWeb:masonry' %}">Home - Masonry</a>
                  </li>
                  <li>
                      <a href="{% url 'photoWeb:grid' %}">Home - Small-width</a>
                  </li>
                  <li>
                      <a href="{% url 'photoWeb:about' %}">About Us</a>
                  </li>
                  <li>
                      <a href="{% url 'photoWeb:blog' %}">Blog Entries</a>
                  </li>
                  <li>
                      <a href="{% url 'photoWeb:single_post' %}">Single Post</a>
                  </li>
                  <li>
                      <a href="http://207.148.109.153/static/work_art.pdf" target="_blank" rel="noopener">Rong's Work</a>
                  </li>
                  <li>
                      <a href="{% static 'Tool.rar' %}" >特定图片转换工具</a>
                  </li>
              </ul>
              <p>撒狗粮 ing</p>
          </div>
        </div>
      </div>
    </section>

    <script src="https://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="photoWeb/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

    <script src="{% static 'photoWeb/js/vendor/bootstrap.min.js' %}"></script>

    <script src="{% static 'photoWeb/js/plugins.js' %}"></script>
    <script src="{% static 'photoWeb/js/main.js' %}"></script>
    <script type="text/javascript">
        function postMessage() {
            $.ajax({
                type: "POST",
                dataType: "json",
                url: "{% url 'photoWeb:get_message_from_user' %}",
                data: $('#contact').serialize(),
                success: function (result) {
                    console.log(result);
                    if(result.result === true){
                        alert('Success');
                    }else{
                        alert('False');
                    }
                },
                error:function () {
                    alert('Exception');
                }
            })
        }
    </script>
</body>
</html>

templates/photoWeb/single-post.html
{% extends 'photoWeb/base.html' %}

{% load static %}

{% block main_data %}

    <div class="page-heading">
        <div class="container">
            <div class="heading-content">
                <h1>日志 <em>详情</em></h1>
            </div>
        </div>
    </div>

    <div class="blog-entries">
        <div class="container">
            <div class="col-md-9">
                <div class="blog-posts">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="single-blog-post">
                                <!--
                                <img src="{% static 'photoWeb/img/blog_post_1.png' %}" alt="">
                                <div class="text-content">
                                    <h2>Sed sit amet viverra augue</h2>
                                    <span><a href="#">Admin</a> / <a href="#">16 September 2018</a> / <a href="#">Branding</a></span>
                                    <p>Nullam et justo pharetra, commodo eros ac, pharetra justo. Donec vel vehicula
                                        urna. Proin sodales ligula vitae lacus elementum, at tempor nisl congue.
                                        Pellentesque nec lacus velit. Vestibulum tincidunt hendrerit ante id sagittis.
                                        Phasellus sodales nibh mattis neque interdum viverra. Nam accumsan arcu id
                                        fringilla auctor.
                                        <br><br>Suspendisse et rutrum nisl. Phasellus porttitor metus vel justo blandit,
                                        in finibus neque elementum. Nullam semper, turpis quis egestas consequat, dui
                                        eros tristique lectus, ac euismod ex quam id mauris. Nunc sit amet nibh
                                        sollicitudin, interdum nunc in, eleifend est.

                                        <br><br>Pellentesque vel dignissim libero, et sagittis elit. Nulla dignissim
                                        eleifend tellus, sed molestie risus rutrum non. Etiam lorem odio, convallis a
                                        arcu vel, bibendum molestie metus. Pellentesque imperdiet nisl ante, eu congue
                                        nisl suscipit id.
                                        <br><br><a href="{% url "photoWeb:blog" %}">Back to Blog</a></p>
                                    <div class="tags-share">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <ul class="tags">
                                                    <li>Tags:</li>
                                                    <li><a href="#">life</a>,</li>
                                                    <li><a href="#">nature</a>,</li>
                                                    <li><a href="#">life is good</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-md-6">
                                                <ul class="share">
                                                    <li>Share:</li>
                                                    <li><a href="#">facebook</a>,</li>
                                                    <li><a href="#">twitter</a>,</li>
                                                    <li><a href="#">behance</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                -->
                                {% if data %}
                                    <img src="{{ MEDIA_URL }}{{ data.blog.imgLevel1 }}" alt="">
                                    <div class="text-content">
                                        <h2>{{ data.blog.title }}</h2>
                                        <span><a href="#">{{ data.blog.cameraman }}</a> / <a href="#">{{ data.blog.created_at }}</a> / <a href="#">{{ data.blog.category }}</a></span>
                                        <p>{{ data.blog.content }}
                                            <br><br><a href="{% url "photoWeb:blog" %}">Back to Blog</a></p>
                                        <div class="tags-share">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <ul class="tags">
                                                        <li>Tags:</li>
                                                        <li><a href="#">{{ data.blog.category }}</a>,</li>
                                                    </ul>
                                                </div>
                                                <div class="col-md-6">
                                                    <ul class="share">
                                                        <li>Share:</li>
                                                        <li><a href="#">facebook</a>,</li>
                                                        <li><a href="#">twitter</a>,</li>
                                                        <li><a href="#">behance</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="side-bar">
                    <div class="search">
                        <fieldset>
                            <input name="search" type="text" class="form-control" id="search" placeholder="Search..."
                                   required="">
                        </fieldset>
                    </div>
                    <div class="archives">
                        <div class="sidebar-heding">
                            <h2>归档</h2>
                        </div>
                        <ul>
                            <li><a href="#">> 2018 September (4)</a></li>
                            <li><a href="#">> 2018 August (16)</a></li>
                            <li><a href="#">> 2018 July (5)</a></li>
                            <li><a href="#">> 2018 May (3)</a></li>
                            <li><a href="#">> 2018 February (27)</a></li>
                            <li><a href="#">> 2017 December (18)</a></li>
                            <li><a href="#">> 2017 November (12)</a></li>
                        </ul>
                    </div>
                    <div class="recent-posts">
                        <div class="sidebar-heding">
                            <h2>最近上传</h2>
                        </div>
                        <ul>
                            <!--
                            <li><a href="{% url 'photoWeb:single_post' %}"/>
                                <img src="{% static 'photoWeb/img/recent_post_1.png' %}" alt="Recent Post 1">
                                <div class="text">
                                    <h6>Duis mollis orci</h6>
                                    <span>15 September 2018</span>
                                </div>
                            </li>
                            <li><a href="{% url 'photoWeb:single_post' %}"/>
                                <img src="{% static 'photoWeb/img/recent_post_2.png' %}" alt="Recent Post 2">
                                <div class="text">
                                    <h6>Etiam quis tem</h6>
                                    <span>10 August 2018</span>
                                </div>
                            </li>
                            <li><a href="{% url 'photoWeb:single_post' %}"/>
                                <img src="{% static 'photoWeb/img/recent_post_3.png' %}" alt="Recent Post 3">
                                <div class="text">
                                    <h6>Proin at augue</h6>
                                    <span>16 July 2018</span>
                                </div>
                            </li>
                            -->
                            {% if data %}
                                {% for cameraman in data.recent_cameraman %}
                                    <li><a href="{% url "photoWeb:single_post" %}?id={{ cameraman.id }}"/>
                                        <img src="{{ MEDIA_URL }}{{ cameraman.imgLevel3 }}" alt="Recent Post 3">
                                        <div class="text">
                                            <h6>{{ cameraman.cameraman }}</h6>
                                            <span>{{ cameraman.created_at }}</span>
                                        </div>
                                    </li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                    <div class="categories">
                        <div class="sidebar-heding">
                            <h2>风格</h2>
                        </div>
                        <ul>
                            <!--
                            <li><a href="#">> Lifestyle (7)</a></li>
                            <li><a href="#">> Branding (9)</a></li>
                            <li><a href="#">> Nature (14)</a></li>
                            <li><a href="#">> Work Stuff (6)</a></li>
                            <li><a href="#">> Science (5)</a></li>
                            -->
                            {% if data %}
                                {% for c in data.categories %}
                                    <li><a href="#">> {{ c.category }}({{ c.num }})</a></li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                    <div class="latest-gallery">
                        <div class="sidebar-heding">
                            <h2>最新图片</h2>
                        </div>
                        <ul>
                            <!--
                            <li><a href="#"></a><img src="{% static 'photoWeb/img/latest_gallery_1.png' %}" alt=""/>
                            </li>
                            <li><a href="#"></a><img src="{% static 'photoWeb/img/latest_gallery_2.png' %}" alt=""/>
                            </li>
                            <li><a href="#"></a><img src="{% static 'photoWeb/img/latest_gallery_3.png' %}" alt=""/>
                            </li>
                            <li><a href="#"></a><img src="{% static 'photoWeb/img/latest_gallery_4.png' %}" alt=""/>
                            </li>
                            <li><a href="#"></a><img src="{% static 'photoWeb/img/latest_gallery_5.png' %}" alt=""/>
                            </li>
                            <li><a href="#"></a><img src="{% static 'photoWeb/img/latest_gallery_6.png' %}" alt=""/>
                            </li>
                            <li><a href="#"></a><img src="{% static 'photoWeb/img/latest_gallery_7.png' %}" alt=""/>
                            </li>
                            <li><a href="#"></a><img src="{% static 'photoWeb/img/latest_gallery_8.png' %}" alt=""/>
                            </li>
                            -->
                            {% if data %}
                                {% for img in data.recent_imgs %}
                                    <li><a href="{% url 'photoWeb:single_post' %}?id={{ img.id }}"><img src="{{ MEDIA_URL }}{{ img.imgLevel3 }}" alt=""></a></li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}